artifacts_directory: artifacts

data_ingestion:
  root_directory: artifacts/data_ingestion
  data_url: "https://www.kaggle.com/datasets/vagifa/ethereum-frauddetection-dataset"
  local_data_path: artifacts/data_ingestion


